baseURL = 'https://ramosprosantiago.cl/'
languageCode = 'es-cl'
title = 'Ramos Propiedades'
theme = 'ananke'
resourceDir = "../resources"

DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 3                  # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true

[params]
text_color = ""
author = "Fabián Villena"
favicon = ""
# site_logo = "/images/logo_cropped.jpg"
description = "En Ramos Propiedades en Santiago, te ofrecemos asesoría personalizada y soluciones efectivas para encontrar el hogar de tus sueños o la inversión perfecta. Con años de experiencia en el mercado local, te acompañamos en cada paso del proceso."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3
